image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (запоминаем информацию о процессе в переменной $App)
  - ps: $App = Start-Process -FilePath java -ArgumentList "-jar ./artifacts/app-ibank.jar -P:profile=test" -PassThru

build_script:
  - ps: chmod +x gradlew
  - ps: ./gradlew test --info "-Dselenide.headless=true"  # стартуем Selenide в Headless-режиме

on_finish:
  - ps: Stop-Process -Id $App.Id  # останавливаем SUT